Repository jjjonesjr33/petlibro, pull requests merged in 2024-11, with the labels that each got.

#23 Add Support for Manual Lid Opening & On/Off of Display Matrix for OneRFIDFeeder PLAF301
  custom_components/petlibro/api.py
  custom_components/petlibro/button.py
  custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py
  custom_components/petlibro/translations/en.json
Labels: Documentation, Enhancement, In review

#34 OneRFID - Sound Level Control, Sound State (on/off), Child Lock (device class change), Display State.
  custom_components/petlibro/__init__.py
  custom_components/petlibro/api.py
  custom_components/petlibro/binary_sensor.py
  custom_components/petlibro/const.py
  custom_components/petlibro/devices/device.py
  custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py
  custom_components/petlibro/number.py
  custom_components/petlibro/sensor.py
  custom_components/petlibro/translations/en.json
Labels: Enhancement, In review

#36 Fixes the displayed amount for the "Today Feeding Quantity" for PETLIBRO Air Smart Feeder (PLAF108)
  custom_components/petlibro/devices/feeders/air_smart_feeder.py
  custom_components/petlibro/sensor.py
Labels: Bug, Enhancement, In review

#35 OneRFID - Reset Dessicant Button + Control Dessicant Frequency
  custom_components/petlibro/api.py
  custom_components/petlibro/button.py
  custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py
  custom_components/petlibro/number.py
  custom_components/petlibro/translations/en.json
Labels: Enhancement, In review
