Repository jjjonesjr33/petlibro, pull requests merged in 2025-08, with the labels that each got.

#98 Feature/Fountains-Filter-Cleaning-Control
  custom_components/petlibro/api.py
  custom_components/petlibro/button.py
  custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py
  custom_components/petlibro/devices/fountains/dockstream_smart_fountain.py
  custom_components/petlibro/devices/fountains/dockstream_smart_rfid_fountain.py
  custom_components/petlibro/number.py
  custom_components/petlibro/translations/ar.json
  custom_components/petlibro/translations/bn.json
  custom_components/petlibro/translations/de.json
  custom_components/petlibro/translations/dk.json
  custom_components/petlibro/translations/en.json
  custom_components/petlibro/translations/es.json
  custom_components/petlibro/translations/fr.json
  custom_components/petlibro/translations/hi.json
  custom_components/petlibro/translations/ja.json
  custom_components/petlibro/translations/nl-be.json
  custom_components/petlibro/translations/pt.json
  custom_components/petlibro/translations/ru.json
  custom_components/petlibro/translations/zh-cn.json
Labels: Enhancement, Completed

#115 Feature/Account-Settings
  custom_components/petlibro/__init__.py
  custom_components/petlibro/api.py
  custom_components/petlibro/config_flow.py
  custom_components/petlibro/const.py
  custom_components/petlibro/hub.py
  custom_components/petlibro/member.py
  custom_components/petlibro/sensor.py
  custom_components/petlibro/translations/en.json
Labels: Enhancement, In review, Ready

#117 Feature/polar-wet-food-feeder-enhanced-plate-control
  custom_components/petlibro/__init__.py
  custom_components/petlibro/api.py
  custom_components/petlibro/devices/feeders/polar_wet_food_feeder.py
  custom_components/petlibro/select.py
  custom_components/petlibro/switch.py
  custom_components/petlibro/translations/en.json
Labels: Hot Fix, Ready, Needs Resolved

#116 Feature/Indicator-Control-Multiple-Devices
  custom_components/petlibro/__init__.py
  custom_components/petlibro/api.py
  custom_components/petlibro/binary_sensor.py
  custom_components/petlibro/button.py
  custom_components/petlibro/devices/feeders/air_smart_feeder.py
  custom_components/petlibro/devices/feeders/granary_smart_camera_feeder.py
  custom_components/petlibro/devices/feeders/granary_smart_feeder.py
  custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py
  custom_components/petlibro/devices/feeders/polar_wet_food_feeder.py
  custom_components/petlibro/devices/feeders/space_smart_feeder.py
  custom_components/petlibro/devices/fountains/dockstream_smart_fountain.py
  custom_components/petlibro/devices/fountains/dockstream_smart_rfid_fountain.py
  custom_components/petlibro/translations/en.json
Labels: Enhancement, Ready, Needs Resolved

#128 Bug/Last-Feed-Time-Fix-Granary+Space-Feeders
  custom_components/petlibro/devices/feeders/granary_smart_feeder.py
  custom_components/petlibro/devices/feeders/space_smart_feeder.py
Labels: Bug, Completed, Hot Fix

#127 feat: GUI enable display debug
  custom_components/petlibro/manifest.json
Labels: Enhancement
